export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
}

export const AIRPORTS: Airport[] = [
  {
    iata: "LHR",
    name: "London Heathrow Airport",
    city: "London",
    country: "United Kingdom",
  },
  {
    iata: "LGW",
    name: "London Gatwick Airport",
    city: "London",
    country: "United Kingdom",
  },
  {
    iata: "STN",
    name: "London Stansted Airport",
    city: "London",
    country: "United Kingdom",
  },
  {
    iata: "MAN",
    name: "Manchester Airport",
    city: "Manchester",
    country: "United Kingdom",
  },
  {
    iata: "EDI",
    name: "Edinburgh Airport",
    city: "Edinburgh",
    country: "United Kingdom",
  },
  {
    iata: "DXB",
    name: "Dubai International Airport",
    city: "Dubai",
    country: "United Arab Emirates",
  },
  {
    iata: "AUH",
    name: "Zayed International Airport",
    city: "Abu Dhabi",
    country: "United Arab Emirates",
  },
  {
    iata: "SHJ",
    name: "Sharjah International Airport",
    city: "Sharjah",
    country: "United Arab Emirates",
  },
  {
    iata: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    country: "United States",
  },
  {
    iata: "EWR",
    name: "Newark Liberty International Airport",
    city: "Newark/New York",
    country: "United States",
  },
  {
    iata: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    country: "United States",
  },
  {
    iata: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    country: "United States",
  },
  {
    iata: "ORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    country: "United States",
  },
  {
    iata: "ATL",
    name: "Hartsfield–Jackson Atlanta International Airport",
    city: "Atlanta",
    country: "United States",
  },
  {
    iata: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    country: "United States",
  },
  {
    iata: "DEN",
    name: "Denver International Airport",
    city: "Denver",
    country: "United States",
  },
  {
    iata: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    country: "United States",
  },
  {
    iata: "SEA",
    name: "Seattle–Tacoma International Airport",
    city: "Seattle",
    country: "United States",
  },
  {
    iata: "LAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    country: "United States",
  },
  {
    iata: "MCO",
    name: "Orlando International Airport",
    city: "Orlando",
    country: "United States",
  },
  {
    iata: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    country: "United States",
  },
  {
    iata: "PHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    country: "United States",
  },
  {
    iata: "IAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    country: "United States",
  },
  {
    iata: "CDG",
    name: "Charles de Gaulle Airport",
    city: "Paris",
    country: "France",
  },
  { iata: "ORY", name: "Paris Orly Airport", city: "Paris", country: "France" },
  {
    iata: "NCE",
    name: "Nice Côte d'Azur Airport",
    city: "Nice",
    country: "France",
  },
  {
    iata: "LYS",
    name: "Lyon–Saint-Exupéry Airport",
    city: "Lyon",
    country: "France",
  },
  {
    iata: "SIN",
    name: "Singapore Changi Airport",
    city: "Singapore",
    country: "Singapore",
  },
  {
    iata: "HND",
    name: "Tokyo Haneda Airport",
    city: "Tokyo",
    country: "Japan",
  },
  {
    iata: "NRT",
    name: "Narita International Airport",
    city: "Tokyo",
    country: "Japan",
  },
  {
    iata: "KIX",
    name: "Kansai International Airport",
    city: "Osaka",
    country: "Japan",
  },
  {
    iata: "HKG",
    name: "Hong Kong International Airport",
    city: "Hong Kong",
    country: "China",
  },
  {
    iata: "PEK",
    name: "Beijing Capital International Airport",
    city: "Beijing",
    country: "China",
  },
  {
    iata: "PKX",
    name: "Beijing Daxing International Airport",
    city: "Beijing",
    country: "China",
  },
  {
    iata: "PVG",
    name: "Shanghai Pudong International Airport",
    city: "Shanghai",
    country: "China",
  },
  {
    iata: "SHA",
    name: "Shanghai Hongqiao International Airport",
    city: "Shanghai",
    country: "China",
  },
  {
    iata: "CAN",
    name: "Guangzhou Baiyun International Airport",
    city: "Guangzhou",
    country: "China",
  },
  {
    iata: "SZX",
    name: "Shenzhen Bao'an International Airport",
    city: "Shenzhen",
    country: "China",
  },
  {
    iata: "FRA",
    name: "Frankfurt Airport",
    city: "Frankfurt",
    country: "Germany",
  },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  {
    iata: "BER",
    name: "Berlin Brandenburg Airport",
    city: "Berlin",
    country: "Germany",
  },
  {
    iata: "DUS",
    name: "Düsseldorf Airport",
    city: "Düsseldorf",
    country: "Germany",
  },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  {
    iata: "AMS",
    name: "Amsterdam Airport Schiphol",
    city: "Amsterdam",
    country: "Netherlands",
  },
  {
    iata: "IST",
    name: "Istanbul Airport",
    city: "Istanbul",
    country: "Turkey",
  },
  {
    iata: "SAW",
    name: "Sabiha Gökçen International Airport",
    city: "Istanbul",
    country: "Turkey",
  },
  {
    iata: "ESB",
    name: "Esenboğa International Airport",
    city: "Ankara",
    country: "Turkey",
  },
  { iata: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey" },
  {
    iata: "DOH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "Qatar",
  },
  {
    iata: "ICN",
    name: "Incheon International Airport",
    city: "Seoul",
    country: "South Korea",
  },
  {
    iata: "GMP",
    name: "Gimpo International Airport",
    city: "Seoul",
    country: "South Korea",
  },
  {
    iata: "SYD",
    name: "Sydney Kingsford Smith Airport",
    city: "Sydney",
    country: "Australia",
  },
  {
    iata: "MEL",
    name: "Melbourne Airport",
    city: "Melbourne",
    country: "Australia",
  },
  {
    iata: "BNE",
    name: "Brisbane Airport",
    city: "Brisbane",
    country: "Australia",
  },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  {
    iata: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    country: "Canada",
  },
  {
    iata: "YVR",
    name: "Vancouver International Airport",
    city: "Vancouver",
    country: "Canada",
  },
  {
    iata: "YUL",
    name: "Montréal–Trudeau International Airport",
    city: "Montreal",
    country: "Canada",
  },
  {
    iata: "CPH",
    name: "Copenhagen Airport",
    city: "Copenhagen",
    country: "Denmark",
  },
  {
    iata: "ZRH",
    name: "Zurich Airport",
    city: "Zurich",
    country: "Switzerland",
  },
  {
    iata: "GVA",
    name: "Geneva Airport",
    city: "Geneva",
    country: "Switzerland",
  },
  {
    iata: "MAD",
    name: "Adolfo Suárez Madrid–Barajas Airport",
    city: "Madrid",
    country: "Spain",
  },
  {
    iata: "BCN",
    name: "Barcelona–El Prat Airport",
    city: "Barcelona",
    country: "Spain",
  },
  {
    iata: "PMI",
    name: "Palma de Mallorca Airport",
    city: "Palma de Mallorca",
    country: "Spain",
  },
  {
    iata: "FCO",
    name: "Leonardo da Vinci–Fiumicino Airport",
    city: "Rome",
    country: "Italy",
  },
  {
    iata: "MXP",
    name: "Milan Malpensa Airport",
    city: "Milan",
    country: "Italy",
  },
  {
    iata: "LIN",
    name: "Milan Linate Airport",
    city: "Milan",
    country: "Italy",
  },
  {
    iata: "VCE",
    name: "Venice Marco Polo Airport",
    city: "Venice",
    country: "Italy",
  },
  {
    iata: "MEX",
    name: "Mexico City International Airport",
    city: "Mexico City",
    country: "Mexico",
  },
  {
    iata: "CUN",
    name: "Cancún International Airport",
    city: "Cancún",
    country: "Mexico",
  },
  {
    iata: "BKK",
    name: "Suvarnabhumi Airport",
    city: "Bangkok",
    country: "Thailand",
  },
  {
    iata: "DMK",
    name: "Don Mueang International Airport",
    city: "Bangkok",
    country: "Thailand",
  },
  {
    iata: "HKT",
    name: "Phuket International Airport",
    city: "Phuket",
    country: "Thailand",
  },
  {
    iata: "DEL",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "India",
  },
  {
    iata: "BOM",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "India",
  },
  {
    iata: "BLR",
    name: "Kempegowda International Airport",
    city: "Bangalore",
    country: "India",
  },
  {
    iata: "MAA",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "India",
  },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "LIS", name: "Lisbon Airport", city: "Lisbon", country: "Portugal" },
  { iata: "OPO", name: "Porto Airport", city: "Porto", country: "Portugal" },
  {
    iata: "HEL",
    name: "Helsinki Airport",
    city: "Helsinki",
    country: "Finland",
  },
  {
    iata: "OSL",
    name: "Oslo Airport, Gardermoen",
    city: "Oslo",
    country: "Norway",
  },
  {
    iata: "ARN",
    name: "Stockholm Arlanda Airport",
    city: "Stockholm",
    country: "Sweden",
  },
  {
    iata: "VIE",
    name: "Vienna International Airport",
    city: "Vienna",
    country: "Austria",
  },
  {
    iata: "ATH",
    name: "Athens International Airport",
    city: "Athens",
    country: "Greece",
  },
  {
    iata: "CAI",
    name: "Cairo International Airport",
    city: "Cairo",
    country: "Egypt",
  },
  {
    iata: "HRG",
    name: "Hurghada International Airport",
    city: "Hurghada",
    country: "Egypt",
  },
  {
    iata: "SSH",
    name: "Sharm El Sheikh International Airport",
    city: "Sharm El Sheikh",
    country: "Egypt",
  },
  {
    iata: "JNB",
    name: "O. R. Tambo International Airport",
    city: "Johannesburg",
    country: "South Africa",
  },
  {
    iata: "CPT",
    name: "Cape Town International Airport",
    city: "Cape Town",
    country: "South Africa",
  },
  {
    iata: "LOS",
    name: "Murtala Muhammed International Airport",
    city: "Lagos",
    country: "Nigeria",
  },
  {
    iata: "ABV",
    name: "Nnamdi Azikiwe International Airport",
    city: "Abuja",
    country: "Nigeria",
  },
  {
    iata: "PHC",
    name: "Port Harcourt International Airport",
    city: "Port Harcourt",
    country: "Nigeria",
  },
  {
    iata: "KAN",
    name: "Mallam Aminu Kano International Airport",
    city: "Kano",
    country: "Nigeria",
  },
  {
    iata: "ACC",
    name: "Kotoka International Airport",
    city: "Accra",
    country: "Ghana",
  },
  {
    iata: "NBO",
    name: "Jomo Kenyatta International Airport",
    city: "Nairobi",
    country: "Kenya",
  },
  {
    iata: "MBA",
    name: "Moi International Airport",
    city: "Mombasa",
    country: "Kenya",
  },
  {
    iata: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
    country: "Malaysia",
  },
  {
    iata: "BKI",
    name: "Kota Kinabalu International Airport",
    city: "Kota Kinabalu",
    country: "Malaysia",
  },
  {
    iata: "AKL",
    name: "Auckland Airport",
    city: "Auckland",
    country: "New Zealand",
  },
  {
    iata: "CHC",
    name: "Christchurch Airport",
    city: "Christchurch",
    country: "New Zealand",
  },
  {
    iata: "EZE",
    name: "Ministro Pistarini International Airport",
    city: "Buenos Aires",
    country: "Argentina",
  },
  {
    iata: "AEP",
    name: "Jorge Newbery Airfield",
    city: "Buenos Aires",
    country: "Argentina",
  },
  {
    iata: "GRU",
    name: "São Paulo/Guarulhos International Airport",
    city: "São Paulo",
    country: "Brazil",
  },
  {
    iata: "CGH",
    name: "São Paulo/Congonhas Airport",
    city: "São Paulo",
    country: "Brazil",
  },
  {
    iata: "GIG",
    name: "Rio de Janeiro/Galeão International Airport",
    city: "Rio de Janeiro",
    country: "Brazil",
  },
  {
    iata: "SDU",
    name: "Santos Dumont Airport",
    city: "Rio de Janeiro",
    country: "Brazil",
  },
  {
    iata: "SCL",
    name: "Comodoro Arturo Merino Benítez International Airport",
    city: "Santiago",
    country: "Chile",
  },
  {
    iata: "BOG",
    name: "El Dorado International Airport",
    city: "Bogotá",
    country: "Colombia",
  },
  {
    iata: "RUH",
    name: "King Khalid International Airport",
    city: "Riyadh",
    country: "Saudi Arabia",
  },
  {
    iata: "JED",
    name: "King Abdulaziz International Airport",
    city: "Jeddah",
    country: "Saudi Arabia",
  },
  {
    iata: "DMM",
    name: "King Fahd International Airport",
    city: "Dammam",
    country: "Saudi Arabia",
  },
  {
    iata: "TLV",
    name: "Ben Gurion Airport",
    city: "Tel Aviv",
    country: "Israel",
  },
  {
    iata: "KWI",
    name: "Kuwait International Airport",
    city: "Kuwait City",
    country: "Kuwait",
  },
  {
    iata: "MCT",
    name: "Muscat International Airport",
    city: "Muscat",
    country: "Oman",
  },
  {
    iata: "BAH",
    name: "Bahrain International Airport",
    city: "Manama",
    country: "Bahrain",
  },
  {
    iata: "AMM",
    name: "Queen Alia International Airport",
    city: "Amman",
    country: "Jordan",
  },
  {
    iata: "BEY",
    name: "Beirut–Rafic Hariri International Airport",
    city: "Beirut",
    country: "Lebanon",
  },
  {
    iata: "ISB",
    name: "Islamabad International Airport",
    city: "Islamabad",
    country: "Pakistan",
  },
  {
    iata: "LHE",
    name: "Allama Iqbal International Airport",
    city: "Lahore",
    country: "Pakistan",
  },
  {
    iata: "KHI",
    name: "Jinnah International Airport",
    city: "Karachi",
    country: "Pakistan",
  },
  {
    iata: "DAC",
    name: "Shahjalal International Airport",
    city: "Dhaka",
    country: "Bangladesh",
  },
  {
    iata: "MLE",
    name: "Velana International Airport",
    city: "Malé",
    country: "Maldives",
  },
  {
    iata: "CMB",
    name: "Bandaranaike International Airport",
    city: "Colombo",
    country: "Sri Lanka",
  },
  {
    iata: "KTM",
    name: "Tribhuvan International Airport",
    city: "Kathmandu",
    country: "Nepal",
  },
  {
    iata: "HAN",
    name: "Noi Bai International Airport",
    city: "Hanoi",
    country: "Vietnam",
  },
  {
    iata: "SGN",
    name: "Tan Son Nhat International Airport",
    city: "Ho Chi Minh City",
    country: "Vietnam",
  },
  {
    iata: "MNL",
    name: "Ninoy Aquino International Airport",
    city: "Manila",
    country: "Philippines",
  },
  {
    iata: "CGK",
    name: "Soekarno–Hatta International Airport",
    city: "Jakarta",
    country: "Indonesia",
  },
  {
    iata: "DPS",
    name: "Ngurah Rai International Airport",
    city: "Bali",
    country: "Indonesia",
  },
  {
    iata: "PRG",
    name: "Václav Havel Airport Prague",
    city: "Prague",
    country: "Czech Republic",
  },
  {
    iata: "WAW",
    name: "Warsaw Chopin Airport",
    city: "Warsaw",
    country: "Poland",
  },
  {
    iata: "BUD",
    name: "Budapest Ferenc Liszt International Airport",
    city: "Budapest",
    country: "Hungary",
  },
  {
    iata: "OTP",
    name: "Henri Coandă International Airport",
    city: "Bucharest",
    country: "Romania",
  },
  {
    iata: "BRU",
    name: "Brussels Airport",
    city: "Brussels",
    country: "Belgium",
  },
  {
    iata: "LUX",
    name: "Luxembourg Airport",
    city: "Luxembourg City",
    country: "Luxembourg",
  },
  {
    iata: "KBP",
    name: "Boryspil International Airport",
    city: "Kyiv",
    country: "Ukraine",
  },
  {
    iata: "BEG",
    name: "Belgrade Nikola Tesla Airport",
    city: "Belgrade",
    country: "Serbia",
  },
  {
    iata: "TIA",
    name: "Tirana International Airport Nënë Tereza",
    city: "Tirana",
    country: "Albania",
  },
  {
    iata: "DOH",
    name: "Hamad International Airport",
    city: "Doha",
    country: "Qatar",
  },
  {
    iata: "KBF",
    name: "King Faisal Air Base",
    city: "Tabuk",
    country: "Saudi Arabia",
  },
  {
    iata: "MED",
    name: "Prince Mohammad bin Abdulaziz International Airport",
    city: "Medina",
    country: "Saudi Arabia",
  },
  {
    iata: "DMM",
    name: "King Fahd International Airport",
    city: "Dammam",
    country: "Saudi Arabia",
  },
  {
    iata: "TPE",
    name: "Taiwan Taoyuan International Airport",
    city: "Taipei",
    country: "Taiwan",
  },
  {
    iata: "KUL",
    name: "Kuala Lumpur International Airport",
    city: "Kuala Lumpur",
    country: "Malaysia",
  },
  {
    iata: "CGK",
    name: "Soekarno-Hatta International Airport",
    city: "Jakarta",
    country: "Indonesia",
  },
  {
    iata: "SUB",
    name: "Juanda International Airport",
    city: "Surabaya",
    country: "Indonesia",
  },
  {
    iata: "SGN",
    name: "Tan Son Nhat International Airport",
    city: "Ho Chi Minh City",
    country: "Vietnam",
  },
  {
    iata: "DAD",
    name: "Da Nang International Airport",
    city: "Da Nang",
    country: "Vietnam",
  },
  {
    iata: "REP",
    name: "Siem Reap International Airport",
    city: "Siem Reap",
    country: "Cambodia",
  },
  {
    iata: "PNH",
    name: "Phnom Penh International Airport",
    city: "Phnom Penh",
    country: "Cambodia",
  },
  {
    iata: "VTE",
    name: "Wattay International Airport",
    city: "Vientiane",
    country: "Laos",
  },
  {
    iata: "RGN",
    name: "Yangon International Airport",
    city: "Yangon",
    country: "Myanmar",
  },
  {
    iata: "MDL",
    name: "Mandalay International Airport",
    city: "Mandalay",
    country: "Myanmar",
  },
  {
    iata: "SEZ",
    name: "Seychelles International Airport",
    city: "Victoria",
    country: "Seychelles",
  },
  {
    iata: "MRU",
    name: "Sir Seewoosagur Ramgoolam International Airport",
    city: "Plaine Magnien",
    country: "Mauritius",
  },
  {
    iata: "TNR",
    name: "Ivato International Airport",
    city: "Antananarivo",
    country: "Madagascar",
  },
  {
    iata: "RUN",
    name: "Roland Garros Airport",
    city: "Sainte-Marie",
    country: "Réunion",
  },
  {
    iata: "DAR",
    name: "Julius Nyerere International Airport",
    city: "Dar es Salaam",
    country: "Tanzania",
  },
  {
    iata: "ZNZ",
    name: "Abeid Amani Karume International Airport",
    city: "Zanzibar City",
    country: "Tanzania",
  },
  {
    iata: "EBB",
    name: "Entebbe International Airport",
    city: "Entebbe",
    country: "Uganda",
  },
  {
    iata: "ADD",
    name: "Addis Ababa Bole International Airport",
    city: "Addis Ababa",
    country: "Ethiopia",
  },
  {
    iata: "KGL",
    name: "Kigali International Airport",
    city: "Kigali",
    country: "Rwanda",
  },
  {
    iata: "BUJ",
    name: "Bujumbura International Airport",
    city: "Bujumbura",
    country: "Burundi",
  },
  {
    iata: "DJI",
    name: "Djibouti–Ambouli International Airport",
    city: "Djibouti City",
    country: "Djibouti",
  },
  {
    iata: "ASM",
    name: "Asmara International Airport",
    city: "Asmara",
    country: "Eritrea",
  },
  {
    iata: "MGQ",
    name: "Aden Adde International Airport",
    city: "Mogadishu",
    country: "Somalia",
  },
  {
    iata: "HGA",
    name: "Egal International Airport",
    city: "Hargeisa",
    country: "Somaliland",
  },
  {
    iata: "KRT",
    name: "Khartoum International Airport",
    city: "Khartoum",
    country: "Sudan",
  },
  {
    iata: "JUB",
    name: "Juba International Airport",
    city: "Juba",
    country: "South Sudan",
  },
  {
    iata: "LOS",
    name: "Murtala Muhammed International Airport",
    city: "Lagos",
    country: "Nigeria",
  },
  {
    iata: "ABV",
    name: "Nnamdi Azikiwe International Airport",
    city: "Abuja",
    country: "Nigeria",
  },
  {
    iata: "PHC",
    name: "Port Harcourt International Airport",
    city: "Port Harcourt",
    country: "Nigeria",
  },
  {
    iata: "KAN",
    name: "Mallam Aminu Kano International Airport",
    city: "Kano",
    country: "Nigeria",
  },
  {
    iata: "ENU",
    name: "Akanu Ibiam International Airport",
    city: "Enugu",
    country: "Nigeria",
  },
  {
    iata: "CBQ",
    name: "Margaret Ekpo International Airport",
    city: "Calabar",
    country: "Nigeria",
  },
  {
    iata: "BNI",
    name: "Benin Airport",
    city: "Benin City",
    country: "Nigeria",
  },
  { iata: "QRW", name: "Warri Airport", city: "Warri", country: "Nigeria" },
  {
    iata: "ILR",
    name: "Ilorin International Airport",
    city: "Ilorin",
    country: "Nigeria",
  },
  {
    iata: "SKBP",
    name: "Sadiq Abubakar III International Airport",
    city: "Sokoto",
    country: "Nigeria",
  },
  { iata: "YOL", name: "Yola Airport", city: "Yola", country: "Nigeria" },
  {
    iata: "MIU",
    name: "Maiduguri International Airport",
    city: "Maiduguri",
    country: "Nigeria",
  },
  { iata: "QUO", name: "Akwa Ibom Airport", city: "Uyo", country: "Nigeria" },
  { iata: "AKURE", name: "Akure Airport", city: "Akure", country: "Nigeria" },
  {
    iata: "IBADAN",
    name: "Ibadan Airport",
    city: "Ibadan",
    country: "Nigeria",
  },
  { iata: "KAT", name: "Katsina Airport", city: "Katsina", country: "Nigeria" },
];
